url=jdbc:postgresql://localhost:5432/intern
username=admin
password=1234
referenceUrl=hibernate:spring:ru.moysklad.intern.entity?dialect=org.hibernate.dialect.PostgreSQLDialect
diffChangeLogFile=src/main/resources/db/changelog/changes/001-init.yaml