services:
  db:
    container_name: intern_db
    image: 'postgres:18-alpine'
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/docker
  # DO NOT USE RIGHT NOW.
  api:
    container_name: api_server
    restart: on-failure
    build: .
    ports:
      - '8080:8080'

volumes:
  postgres-data: